using Microsoft.Data.Sqlite;
using PcActivityTracker.Core.Domain;
using PcActivityTracker.Data;
using Xunit;

namespace PcActivityTracker.Data.IntegrationTests;

public sealed class SqliteIntegrationTests : IDisposable
{
    private readonly string path = Path.Combine(Path.GetTempPath(), $"pcactivity-{Guid.NewGuid():N}.db");
    private static readonly UtcInstant Now = new(new DateTimeOffset(2026, 8, 14, 12, 0, 0, TimeSpan.Zero));
    public void Dispose() { SqliteConnection.ClearAllPools(); foreach (var suffix in new[] { "", "-wal", "-shm" }) File.Delete(path + suffix); }

    [Fact] public async Task NewDatabaseMigratesToLatestSchema() { var db = await Create(); Assert.Equal(SqliteDatabase.CurrentSchemaVersion, await db.GetSchemaVersionAsync()); }
    [Fact] public async Task InitializeCanReopenDatabase() { await Create(); var reopened = new SqliteDatabase(path); await reopened.InitializeAsync(); Assert.Equal(1, await reopened.GetSchemaVersionAsync()); }
    [Fact] public async Task ObservationRoundTrips() { var db = await Create(); var store = new SqliteActivityStore(db); var value = Observation(); await store.AddObservationAsync(value); var found = await store.GetObservationsAsync(new(new(Now.Value.AddMinutes(-1)), new(Now.Value.AddMinutes(1)))); Assert.Equal(value, Assert.Single(found)); }
    [Fact] public async Task ActivityIntervalRoundTrips() { var db = await Create(); var store = new SqliteActivityStore(db); var observation = Observation(); await store.AddObservationAsync(observation); var interval = new ActivityInterval(ActivityIntervalId.New(), observation.Id, new(Now, new(Now.Value.AddMinutes(2))), ActivityState.Active); await store.AddActivityIntervalAsync(interval); Assert.Equal(interval, Assert.Single(await store.GetActivityIntervalsAsync(new(Now, new(Now.Value.AddHours(1)))))); }
    [Fact] public async Task ForeignKeysRejectOrphanInterval() { var db = await Create(); var store = new SqliteActivityStore(db); var interval = new ActivityInterval(ActivityIntervalId.New(), ObservationId.New(), new(Now, new(Now.Value.AddMinutes(1))), ActivityState.Active); await Assert.ThrowsAsync<SqliteException>(() => store.AddActivityIntervalAsync(interval)); }
    [Fact] public async Task IntegrityRejectsOrphanClassification() { var db = await Create(); var store = new SqliteActivityStore(db); var classification = new Classification(ClassificationId.New(), ClassificationTargetType.Observation, Guid.NewGuid(), ClassificationProvenance.Manual, Now, "orfana"); await Assert.ThrowsAsync<SqliteException>(() => store.AddClassificationAsync(classification)); }
    [Fact] public async Task IntegrityAcceptsIntervalTargetAndRejectsMissingIntervalTarget() { var db = await Create(); var store = new SqliteActivityStore(db); var observation = Observation(); await store.AddObservationAsync(observation); var interval = new ActivityInterval(ActivityIntervalId.New(), observation.Id, new(Now, new(Now.Value.AddMinutes(1))), ActivityState.Active); await store.AddActivityIntervalAsync(interval); var valid = new Classification(ClassificationId.New(), ClassificationTargetType.ActivityInterval, interval.Id.Value, ClassificationProvenance.Manual, Now, "valida"); await store.AddClassificationAsync(valid); Assert.Equal(valid, Assert.Single(await store.GetClassificationsAsync(ClassificationTargetType.ActivityInterval, interval.Id.Value))); var missing = new Classification(ClassificationId.New(), ClassificationTargetType.ActivityInterval, Guid.NewGuid(), ClassificationProvenance.Manual, Now, "orfana"); await Assert.ThrowsAsync<SqliteException>(() => store.AddClassificationAsync(missing)); }
    [Fact] public async Task ClassificationDoesNotRewriteObservation() { var db = await Create(); var store = new SqliteActivityStore(db); var observation = Observation(); await store.AddObservationAsync(observation); var classification = new Classification(ClassificationId.New(), ClassificationTargetType.Observation, observation.Id.Value, ClassificationProvenance.Manual, Now, "correzione"); await store.AddClassificationAsync(classification); Assert.Equal(classification, Assert.Single(await store.GetClassificationsAsync(ClassificationTargetType.Observation, observation.Id.Value))); Assert.Equal(observation, Assert.Single(await store.GetObservationsAsync(new(new(Now.Value.AddMinutes(-1)), new(Now.Value.AddMinutes(1)))))); }
    [Fact] public async Task TaxonomyAndExclusionsRoundTrip() { var db = await Create(); var store = new SqliteActivityStore(db); var project = new Project(ProjectId.New(), "Tracker"); var job = new Job(JobId.New(), project.Id, "Sprint 01"); var category = new Category(CategoryId.New(), "Sviluppo"); var exclusion = new ExclusionRule(ExclusionRuleId.New(), ExclusionKind.Application, "password-manager"); await store.SaveProjectAsync(project); await store.SaveJobAsync(job); await store.SaveCategoryAsync(category); await store.SaveExclusionAsync(exclusion); Assert.Equal(project, Assert.Single(await store.GetProjectsAsync())); Assert.Equal(job, Assert.Single(await store.GetJobsAsync(project.Id))); Assert.Equal(category, Assert.Single(await store.GetCategoriesAsync())); Assert.Equal(exclusion, Assert.Single(await store.GetExclusionsAsync())); }
    [Fact] public async Task RetentionDeletesIntervalEntirelyBeforeCutoff() { var db = await Create(); var store = new SqliteActivityStore(db); var observation = Observation(new(Now.Value.AddHours(-2))); await store.AddObservationAsync(observation); await store.AddActivityIntervalAsync(new(ActivityIntervalId.New(), observation.Id, new(observation.ObservedAt, new(Now.Value.AddHours(-1))), ActivityState.Active)); await store.DeleteActivityBeforeAsync(Now); Assert.Empty(await store.GetActivityIntervalsAsync(new(new(Now.Value.AddHours(-3)), new(Now.Value.AddHours(1))))); }
    [Fact] public async Task RetentionPreservesIntervalEntirelyAfterCutoff() { var db = await Create(); var store = new SqliteActivityStore(db); var observation = Observation(new(Now.Value.AddMinutes(1))); await store.AddObservationAsync(observation); var interval = new ActivityInterval(ActivityIntervalId.New(), observation.Id, new(observation.ObservedAt, new(Now.Value.AddMinutes(2))), ActivityState.Active); await store.AddActivityIntervalAsync(interval); await store.DeleteActivityBeforeAsync(Now); Assert.Equal(interval, Assert.Single(await store.GetActivityIntervalsAsync(new(Now, new(Now.Value.AddHours(1)))))); }
    [Fact] public async Task RetentionTrimsCrossingIntervalAndDetachesDeletedEvidence() { var db = await Create(); var store = new SqliteActivityStore(db); var observation = Observation(new(Now.Value.AddHours(-1))); await store.AddObservationAsync(observation); var interval = new ActivityInterval(ActivityIntervalId.New(), observation.Id, new(observation.ObservedAt, new(Now.Value.AddHours(1))), ActivityState.Active); await store.AddActivityIntervalAsync(interval); await store.DeleteActivityBeforeAsync(Now); var retained = Assert.Single(await store.GetActivityIntervalsAsync(new(Now, new(Now.Value.AddHours(2))))); Assert.Equal(Now, retained.Period.Start); Assert.Null(retained.ObservationId); }
    [Fact] public async Task RetentionDeletesClassificationsOfDeletedTargets() { var db = await Create(); var store = new SqliteActivityStore(db); var observation = Observation(new(Now.Value.AddHours(-2))); await store.AddObservationAsync(observation); var interval = new ActivityInterval(ActivityIntervalId.New(), observation.Id, new(observation.ObservedAt, new(Now.Value.AddHours(-1))), ActivityState.Active); await store.AddActivityIntervalAsync(interval); await store.AddClassificationAsync(new(ClassificationId.New(), ClassificationTargetType.Observation, observation.Id.Value, ClassificationProvenance.Manual, Now, "osservazione")); await store.AddClassificationAsync(new(ClassificationId.New(), ClassificationTargetType.ActivityInterval, interval.Id.Value, ClassificationProvenance.Manual, Now, "intervallo")); await store.DeleteActivityBeforeAsync(Now); Assert.Empty(await store.GetClassificationsAsync(ClassificationTargetType.Observation, observation.Id.Value)); Assert.Empty(await store.GetClassificationsAsync(ClassificationTargetType.ActivityInterval, interval.Id.Value)); }
    [Fact] public async Task ObservationImmutableTriggerRejectsUpdate() { await Create(); var store = new SqliteActivityStore(new(path)); var observation = Observation(); await store.AddObservationAsync(observation); await using var connection = Open(); await using var command = connection.CreateCommand(); command.CommandText = "UPDATE observations SET process_name='changed' WHERE id=$id;"; command.Parameters.AddWithValue("$id", observation.Id.Value); var error = await Assert.ThrowsAsync<SqliteException>(() => command.ExecuteNonQueryAsync()); Assert.Contains("immutable", error.Message, StringComparison.OrdinalIgnoreCase); }
    [Fact] public async Task DatabaseRejectsPrivateRawActivity() { await Create(); await using var connection = Open(); await using var command = connection.CreateCommand(); command.CommandText = "INSERT INTO observations(id,source,observed_at_utc,time_zone_id,observed_offset_minutes,state,process_name) VALUES($id,0,$at,'UTC',0,5,'secret');"; command.Parameters.AddWithValue("$id", Guid.NewGuid().ToString()); command.Parameters.AddWithValue("$at", Now.Value.ToString("O")); await Assert.ThrowsAsync<SqliteException>(() => command.ExecuteNonQueryAsync()); }
    [Fact] public async Task PrivateGapRoundTripsWithoutIdentifyingContent() { var db = await Create(); var store = new SqliteActivityStore(db); var gap = new ActivityGap(ActivityGapId.New(), new(Now, new(Now.Value.AddMinutes(10))), ActivityState.Private); await store.AddActivityGapAsync(gap); Assert.Equal(gap, Assert.Single(await store.GetActivityGapsAsync(new(Now, new(Now.Value.AddHours(1)))))); }
    [Fact] public async Task DatabaseRejectsProjectAndJobTogether() { var db = await Create(); var store = new SqliteActivityStore(db); var observation = Observation(); await store.AddObservationAsync(observation); var first = new Project(ProjectId.New(), "first"); var second = new Project(ProjectId.New(), "second"); var job = new Job(JobId.New(), second.Id, "job"); await store.SaveProjectAsync(first); await store.SaveProjectAsync(second); await store.SaveJobAsync(job); await using var connection = Open(); await using var command = connection.CreateCommand(); command.CommandText = "INSERT INTO classifications(id,target_type,target_id,provenance,classified_at_utc,rationale,project_id,job_id) VALUES($id,0,$target,0,$at,'incoerente',$project,$job);"; command.Parameters.AddWithValue("$id", Guid.NewGuid().ToString()); command.Parameters.AddWithValue("$target", observation.Id.Value); command.Parameters.AddWithValue("$at", Now.Value.ToString("O")); command.Parameters.AddWithValue("$project", first.Id.Value); command.Parameters.AddWithValue("$job", job.Id.Value); await Assert.ThrowsAsync<SqliteException>(() => command.ExecuteNonQueryAsync()); }
    [Fact]
    public async Task DatabaseRejectsEmptyTaxonomyIdentifiers()
    {
        var database = await Create();
        var store = new SqliteActivityStore(database);
        var project = new Project(ProjectId.New(), "valid");
        await store.SaveProjectAsync(project);
        await using var connection = Open();
        await using var projectIdCommand = connection.CreateCommand();
        projectIdCommand.CommandText = "SELECT id FROM projects LIMIT 1;";
        var persistedProjectId = (string)(await projectIdCommand.ExecuteScalarAsync())!;
        var statements = new[]
        {
            "INSERT INTO projects VALUES('00000000-0000-0000-0000-000000000000','bad');",
            "INSERT INTO categories VALUES('00000000-0000-0000-0000-000000000000','bad');",
            $"INSERT INTO jobs VALUES('00000000-0000-0000-0000-000000000000','{persistedProjectId}','bad');",
        };
        foreach (var sql in statements)
        {
            await using var command = connection.CreateCommand();
            command.CommandText = sql;
            await Assert.ThrowsAsync<SqliteException>(() => command.ExecuteNonQueryAsync());
        }
    }
    [Fact] public async Task ExpectedIndexesAndWalExist() { await Create(); await using var connection = Open(); var indexes = await Strings(connection, "SELECT name FROM sqlite_master WHERE type='index';"); Assert.Contains("ix_observations_time", indexes); Assert.Contains("ix_activity_intervals_time", indexes); Assert.Contains("ix_classifications_project", indexes); await using var command = connection.CreateCommand(); command.CommandText = "PRAGMA journal_mode;"; Assert.Equal("wal", await command.ExecuteScalarAsync()); }
    [Fact] public async Task FailedMigrationRollsBackAtomically() { var migrations = new[] { new SqliteMigration(1, "CREATE TABLE stable(id INTEGER);"), new SqliteMigration(2, "CREATE TABLE partial(id INTEGER); INVALID SQL;") }; var db = new SqliteDatabase(path, migrations); await Assert.ThrowsAsync<SqliteException>(() => db.InitializeAsync()); await using var connection = Open(); Assert.DoesNotContain("partial", await Strings(connection, "SELECT name FROM sqlite_master WHERE type='table';")); await using var command = connection.CreateCommand(); command.CommandText = "SELECT version FROM schema_info;"; Assert.Equal(1L, await command.ExecuteScalarAsync()); }
    [Fact] public async Task InterruptedTransactionLeavesNoPartialRows() { await Create(); await using (var connection = Open()) { await using var transaction = await connection.BeginTransactionAsync(); await using var command = connection.CreateCommand(); command.Transaction = (SqliteTransaction)transaction; command.CommandText = "INSERT INTO categories VALUES('one','one'); INSERT INTO categories VALUES('two','two');"; await command.ExecuteNonQueryAsync(); await transaction.RollbackAsync(); } await using var reopened = Open(); await using var count = reopened.CreateCommand(); count.CommandText = "SELECT count(*) FROM categories;"; Assert.Equal(0L, await count.ExecuteScalarAsync()); }

    private async Task<SqliteDatabase> Create() { var db = new SqliteDatabase(path); await db.InitializeAsync(); return db; }
    private SqliteConnection Open() { var c = new SqliteConnection($"Data Source={path}"); c.Open(); return c; }
    private static RawObservation Observation(UtcInstant? at = null) => new(ObservationId.New(), ObservationSource.ForegroundApplication, at ?? Now, new("Europe/Rome", TimeSpan.FromHours(2)), ActivityState.Active, new("editor", "/opt/editor"));
    private static async Task<List<string>> Strings(SqliteConnection c, string sql) { await using var command = c.CreateCommand(); command.CommandText = sql; var result = new List<string>(); await using var reader = await command.ExecuteReaderAsync(); while (await reader.ReadAsync()) result.Add(reader.GetString(0)); return result; }
}
