using Microsoft.Data.Sqlite;
using PcActivityTracker.Core.Domain;
using PcActivityTracker.Data;
using Xunit;

namespace PcActivityTracker.Data.IntegrationTests;

public sealed class SqliteIntegrationTests : IDisposable
{
    private readonly string path = Path.Combine(Path.GetTempPath(), $"pcactivity-{Guid.NewGuid():N}.db");
    private static readonly UtcInstant Now = new(new DateTimeOffset(2026, 8, 14, 12, 0, 0, TimeSpan.Zero));
    public void Dispose() { SqliteConnection.ClearAllPools(); foreach (var suffix in new[] { "", "-wal", "-shm" }) File.Delete(path + suffix); }

    [Fact] public async Task NewDatabaseMigratesToLatestSchema() { var db = await Create(); Assert.Equal(SqliteDatabase.CurrentSchemaVersion, await db.GetSchemaVersionAsync()); }
    [Fact] public async Task InitializeCanReopenDatabase() { await Create(); var reopened = new SqliteDatabase(path); await reopened.InitializeAsync(); Assert.Equal(1, await reopened.GetSchemaVersionAsync()); }
    [Fact] public async Task ObservationRoundTrips() { var db = await Create(); var store = new SqliteActivityStore(db); var value = Observation(); await store.AddObservationAsync(value); var found = await store.GetObservationsAsync(new(new(Now.Value.AddMinutes(-1)), new(Now.Value.AddMinutes(1)))); Assert.Equal(value, Assert.Single(found)); }
    [Fact] public async Task ActivityIntervalRoundTrips() { var db = await Create(); var store = new SqliteActivityStore(db); var observation = Observation(); await store.AddObservationAsync(observation); var interval = new ActivityInterval(ActivityIntervalId.New(), observation.Id, new(Now, new(Now.Value.AddMinutes(2))), ActivityState.Active); await store.AddActivityIntervalAsync(interval); Assert.Equal(interval, Assert.Single(await store.GetActivityIntervalsAsync(new(Now, new(Now.Value.AddHours(1)))))); }
    [Fact] public async Task ForeignKeysRejectOrphanInterval() { var db = await Create(); var store = new SqliteActivityStore(db); var interval = new ActivityInterval(ActivityIntervalId.New(), ObservationId.New(), new(Now, new(Now.Value.AddMinutes(1))), ActivityState.Active); await Assert.ThrowsAsync<SqliteException>(() => store.AddActivityIntervalAsync(interval)); }
    [Fact] public async Task IntegrityRejectsOrphanClassification() { var db = await Create(); var store = new SqliteActivityStore(db); var classification = new Classification(ClassificationId.New(), ClassificationTargetType.Observation, Guid.NewGuid(), ClassificationProvenance.Manual, Now, "orfana"); await Assert.ThrowsAsync<SqliteException>(() => store.AddClassificationAsync(classification)); }
    [Fact] public async Task ClassificationDoesNotRewriteObservation() { var db = await Create(); var store = new SqliteActivityStore(db); var observation = Observation(); await store.AddObservationAsync(observation); var classification = new Classification(ClassificationId.New(), ClassificationTargetType.Observation, observation.Id.Value, ClassificationProvenance.Manual, Now, "correzione"); await store.AddClassificationAsync(classification); Assert.Equal(classification, Assert.Single(await store.GetClassificationsAsync(ClassificationTargetType.Observation, observation.Id.Value))); Assert.Equal(observation, Assert.Single(await store.GetObservationsAsync(new(new(Now.Value.AddMinutes(-1)), new(Now.Value.AddMinutes(1)))))); }
    [Fact] public async Task TaxonomyAndExclusionsRoundTrip() { var db = await Create(); var store = new SqliteActivityStore(db); var project = new Project(ProjectId.New(), "Tracker"); var job = new Job(JobId.New(), project.Id, "Sprint 01"); var category = new Category(CategoryId.New(), "Sviluppo"); var exclusion = new ExclusionRule(ExclusionRuleId.New(), ExclusionKind.Application, "password-manager"); await store.SaveProjectAsync(project); await store.SaveJobAsync(job); await store.SaveCategoryAsync(category); await store.SaveExclusionAsync(exclusion); Assert.Equal(project, Assert.Single(await store.GetProjectsAsync())); Assert.Equal(job, Assert.Single(await store.GetJobsAsync(project.Id))); Assert.Equal(category, Assert.Single(await store.GetCategoriesAsync())); Assert.Equal(exclusion, Assert.Single(await store.GetExclusionsAsync())); }
    [Fact] public async Task RetentionCascadesIntervalsAndClassificationsRemainIndependent() { var db = await Create(); var store = new SqliteActivityStore(db); var old = Observation(new(Now.Value.AddDays(-2))); await store.AddObservationAsync(old); await store.AddActivityIntervalAsync(new(ActivityIntervalId.New(), old.Id, new(old.ObservedAt, new(old.ObservedAt.Value.AddMinutes(1))), ActivityState.Active)); Assert.Equal(1, await store.DeleteActivityBeforeAsync(new(Now.Value.AddDays(-1)))); Assert.Empty(await store.GetActivityIntervalsAsync(new(new(Now.Value.AddDays(-3)), Now))); }
    [Fact] public async Task ExpectedIndexesAndWalExist() { await Create(); await using var connection = Open(); var indexes = await Strings(connection, "SELECT name FROM sqlite_master WHERE type='index';"); Assert.Contains("ix_observations_time", indexes); Assert.Contains("ix_activity_intervals_time", indexes); Assert.Contains("ix_classifications_project", indexes); await using var command = connection.CreateCommand(); command.CommandText = "PRAGMA journal_mode;"; Assert.Equal("wal", await command.ExecuteScalarAsync()); }
    [Fact] public async Task FailedMigrationRollsBackAtomically() { var migrations = new[] { new SqliteMigration(1, "CREATE TABLE stable(id INTEGER);"), new SqliteMigration(2, "CREATE TABLE partial(id INTEGER); INVALID SQL;") }; var db = new SqliteDatabase(path, migrations); await Assert.ThrowsAsync<SqliteException>(() => db.InitializeAsync()); await using var connection = Open(); Assert.DoesNotContain("partial", await Strings(connection, "SELECT name FROM sqlite_master WHERE type='table';")); await using var command = connection.CreateCommand(); command.CommandText = "SELECT version FROM schema_info;"; Assert.Equal(1L, await command.ExecuteScalarAsync()); }
    [Fact] public async Task InterruptedTransactionLeavesNoPartialRows() { await Create(); await using (var connection = Open()) { await using var transaction = await connection.BeginTransactionAsync(); await using var command = connection.CreateCommand(); command.Transaction = (SqliteTransaction)transaction; command.CommandText = "INSERT INTO categories VALUES('one','one'); INSERT INTO categories VALUES('two','two');"; await command.ExecuteNonQueryAsync(); await transaction.RollbackAsync(); } await using var reopened = Open(); await using var count = reopened.CreateCommand(); count.CommandText = "SELECT count(*) FROM categories;"; Assert.Equal(0L, await count.ExecuteScalarAsync()); }

    private async Task<SqliteDatabase> Create() { var db = new SqliteDatabase(path); await db.InitializeAsync(); return db; }
    private SqliteConnection Open() { var c = new SqliteConnection($"Data Source={path}"); c.Open(); return c; }
    private static RawObservation Observation(UtcInstant? at = null) => new(ObservationId.New(), ObservationSource.ForegroundApplication, at ?? Now, new("Europe/Rome", TimeSpan.FromHours(2)), ActivityState.Active, new("editor", "/opt/editor"));
    private static async Task<List<string>> Strings(SqliteConnection c, string sql) { await using var command = c.CreateCommand(); command.CommandText = sql; var result = new List<string>(); await using var reader = await command.ExecuteReaderAsync(); while (await reader.ReadAsync()) result.Add(reader.GetString(0)); return result; }
}
